<a href="https://colab.research.google.com/github/vidisha-hub/Week-2/blob/main/emoji_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [5]:
train = pd.read_csv(r'/content/drive/MyDrive/train_emoji.csv',header=None)
train.head()

0  1   2     3
0           never talk to me again  3 NaN   NaN
1  I am proud of your achievements  2 NaN   NaN
2   It is the worst day in my life  3 NaN   NaN
3                 Miss you so much  0 NaN   [0]
4                     food is life  4 NaN   NaN

In [6]:
test = pd.read_csv(r'/content/drive/MyDrive/test_emoji.csv',header=None)
test.head()

0  1
0             I want to eat\t  4
1         he did not answer\t  3
2            he got a raise\t  2
3      she got me a present\t  0
4  ha ha ha it was so funny\t  2

In [7]:
!pip install emoji


     |████████████████████████████████| 170 kB 8.2 MB/s 
  Created wheel for emoji: filename=emoji-1.6.1-py3-none-any.whl size=169314 sha256=d73591acab3d696f348bd3031b912e3c8260946d39132d63dc871c711e03700b
  Stored in directory: /root/.cache/pip/wheels/ea/5f/d3/03d313ddb3c2a1a427bb4690f1621eea60fe6f2a30cc95940f
Successfully built emoji


In [8]:
import emoji

In [9]:
emoji.EMOJI_UNICODE['en']

{':1st_place_medal:': '🥇',
 ':2nd_place_medal:': '🥈',
 ':3rd_place_medal:': '🥉',
 ':AB_button_(blood_type):': '🆎',
 ':ATM_sign:': '🏧',
 ':A_button_(blood_type):': '🅰️',
 ':Afghanistan:': '🇦🇫',
 ':Albania:': '🇦🇱',
 ':Algeria:': '🇩🇿',
 ':American_Samoa:': '🇦🇸',
 ':Andorra:': '🇦🇩',
 ':Angola:': '🇦🇴',
 ':Anguilla:': '🇦🇮',
 ':Antarctica:': '🇦🇶',
 ':Antigua_&_Barbuda:': '🇦🇬',
 ':Aquarius:': '♒',
 ':Argentina:': '🇦🇷',
 ':Aries:': '♈',
 ':Armenia:': '🇦🇲',
 ':Aruba:': '🇦🇼',
 ':Ascension_Island:': '🇦🇨',
 ':Australia:': '🇦🇺',
 ':Austria:': '🇦🇹',
 ':Azerbaijan:': '🇦🇿',
 ':BACK_arrow:': '🔙',
 ':B_button_(blood_type):': '🅱️',
 ':Bahamas:': '🇧🇸',
 ':Bahrain:': '🇧🇭',
 ':Bangladesh:': '🇧🇩',
 ':Barbados:': '🇧🇧',
 ':Belarus:': '🇧🇾',
 ':Belgium:': '🇧🇪',
 ':Belize:': '🇧🇿',
 ':Benin:': '🇧🇯',
 ':Bermuda:': '🇧🇲',
 ':Bhutan:': '🇧🇹',
 ':Bolivia:': '🇧🇴',
 ':Bosnia_&_Herzegovina:': '🇧🇦',
 ':Botswana:': '🇧🇼',
 ':Bouvet_Island:': '🇧🇻',
 ':Brazil:': '🇧🇷',
 ':British_Indian_Ocean_Territory:': '🇮🇴',
 ':British_Virgin_

In [10]:
emoji.emojize(":fearful_face:")

'😨'

In [11]:
emoji_dict = {
    "0":':disappointed_face:' ,
    "1":':brown_heart:' ,
    "2":':1st_place_medal:' ,
    "3": ':face_with_symbols_on_mouth:' ,
    "4":':beating_heart:' ,
}


In [12]:
for e in emoji_dict.values():
    print(emoji.emojize(e), end = " ")

😞 🤎 🥇 🤬 💓 

In [13]:
x_train = train[0].values
y_train = train[1].values

In [14]:
x_train[:10]

array(['never talk to me again', 'I am proud of your achievements',
       'It is the worst day in my life', 'Miss you so much',
       'food is life', 'I love you mum', 'Stop saying bullshit',
       'congratulations on your acceptance',
       'The assignment is too long ', 'I want to go play'], dtype=object)

In [15]:
y_train[:10]

array([3, 2, 3, 0, 4, 0, 3, 2, 3, 1])

In [16]:
x_train.shape , y_train.shape

((132,), (132,))

In [17]:
f = open(r'/content/drive/MyDrive/glove.6B.50d.txt', encoding="utf-8", mode='r')

In [18]:
embedding_matrix = { }

In [19]:
for line in f:
    
    values = line.split()
    word = values[0]
    emb = np.array(values[1:], dtype= 'float')
    
    embedding_matrix[word] = emb

In [20]:
embedding_matrix['!!'].shape

(50,)

In [21]:
def get_embedding_matrix_for_data(data):
    maxLen = 10
    embedding_data = np.zeros( (len(data), maxLen, 50) )
    
    for ix in range(data.shape[0]):
        words_in_sen = data[ix].split()
        
        for ij in range(len(words_in_sen)):
            if embedding_matrix.get(words_in_sen[ij].lower()) is not None:
                embedding_data[ix][ij] = embedding_matrix[words_in_sen[ij].lower()]
                
                return embedding_data

In [22]:
x_train = get_embedding_matrix_for_data(x_train)

In [23]:
x_train

array([[[ 0.095387, -0.16865 , -0.11514 , ..., -0.42103 , -0.53817 ,
          0.13738 ],
        [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
          0.      ],
        [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
          0.      ],
        ...,
        [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
          0.      ],
        [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
          0.      ],
        [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
          0.      ]],

       [[ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
          0.      ],
        [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
          0.      ],
        [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
          0.      ],
        ...,
        [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
          0.      ],
        [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
   

In [24]:
x_train.shape

(132, 10, 50)

In [25]:
from keras.utils.np_utils import to_categorical

In [26]:
y_train = to_categorical(y_train)

In [27]:
y_train

array([[0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0.

In [28]:
from keras.models import Sequential
import keras
from keras.layers import LSTM, SimpleRNN, Dense, Dropout

In [40]:
model = Sequential()
model.add(LSTM(units= 128, input_shape= (10,50), return_sequences= True))

model.add(Dropout(0.5))

model.add(LSTM(units= 128))

model.add(Dropout(0.5))

model.add(Dense(units=10, activation='relu'))

model.add(Dense(units= 5, activation= 'softmax'))



model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_6 (LSTM)               (None, 10, 128)           91648     
                                                                 
 dropout_6 (Dropout)         (None, 10, 128)           0         
                                                                 
 lstm_7 (LSTM)               (None, 128)               131584    
                                                                 
 dropout_7 (Dropout)         (None, 128)               0         
                                                                 
 dense_7 (Dense)             (None, 10)                1290      
                                                                 
 dense_8 (Dense)             (None, 5)                 55        
                                                                 
Total params: 224,577
Trainable params: 224,577
Non-tr

In [41]:
model.compile(optimizer= 'adam', loss = keras.losses.categorical_crossentropy , metrics=['acc'])

In [42]:
his = model.fit(x_train, y_train, validation_split= 0.1, batch_size= 32, epochs= 50)

Epoch 1/50
4/4 [==============================] - 5s 323ms/step - loss: 1.6088 - acc: 0.2288 - val_loss: 1.6101 - val_acc: 0.2857
Epoch 2/50
4/4 [==============================] - 0s 39ms/step - loss: 1.5994 - acc: 0.2797 - val_loss: 1.6175 - val_acc: 0.2857
Epoch 3/50
4/4 [==============================] - 0s 39ms/step - loss: 1.5780 - acc: 0.2797 - val_loss: 1.6433 - val_acc: 0.2857
Epoch 4/50
4/4 [==============================] - 0s 37ms/step - loss: 1.5435 - acc: 0.2627 - val_loss: 1.7430 - val_acc: 0.2857
Epoch 5/50
4/4 [==============================] - 0s 36ms/step - loss: 1.5696 - acc: 0.2797 - val_loss: 1.8025 - val_acc: 0.2857
Epoch 6/50
4/4 [==============================] - 0s 36ms/step - loss: 1.5487 - acc: 0.2712 - val_loss: 1.6970 - val_acc: 0.2857
Epoch 7/50
4/4 [==============================] - 0s 39ms/step - loss: 1.5410 - acc: 0.3220 - val_loss: 1.6645 - val_acc: 0.2857
Epoch 8/50
4/4 [==============================] - 0s 38ms/step - loss: 1.5444 - acc: 0.2881 - va

In [46]:
test[0] = test[0].apply(lambda x : x[:-1])

x_test = test[0].values
y_test = test[1].values

In [48]:
x_test = get_embedding_matrix_for_data(x_test)

y_test = to_categorical(y_test)

In [49]:
model.evaluate(x_test, y_test)[1]*100

2/2 [==============================] - 0s 12ms/step - loss: 1.6599 - acc: 0.3214


32.14285671710968